### ISSUE TITLE
World loading / closing got stuck (on mac os)

### ISSUE THREAD

**Issue by Endermanbugzjfc** [df-mc/dragonfly#148]
The world neither loads nor close successfully. 

### When a player joins, no chunks will be sent to the client.
![IMG_4E7FB10EE251-1](https://user-images.githubusercontent.com/53002741/120493530-9df9ee80-c3ed-11eb-87a3-9907c0fb66e4.jpeg)

### When the server shuts down, it stuck at the closing world state.
![image](https://user-images.githubusercontent.com/53002741/120493724-c71a7f00-c3ed-11eb-8ce2-cf822fa88c94.png)

Not sure if this is an issue with macOS or this will also happen to other operating systems.

# How to reproduce
1. Git clone https://github.com/df-mc/template
2. Execute command `go run main.go`
3. Join the server with an MCBE client
4. Press ctrl+c

# Environment
DragonFly: v0.0.5 (e073ce890c910e99ead39afa18ed2d3f279cc9cb)
Operating system: macOS Big Sur 11.4
Minecraft Bedrock Edition: 1.16.221 (Protocol 431)

# config.toml
```toml

[Network]
  Address = ":19132"

[Server]
  AuthEnabled = true
  JoinMessage = "%v has joined the game"
  MaximumPlayers = 0
  Name = "Dragonfly Server"
  QuitMessage = "%v has left the game"
  ShutdownMessage = "Server closed."

[World]
  Folder = "world"
  MaximumChunkRadius = 32
  Name = "World"
  SimulationDistance = 8
```

# [world.zip](https://github.com/df-mc/dragonfly/files/6585096/world.zip)
https://github.com/df-mc/dragonfly/files/6585096/world.zip
*(Also tried deleting the world and generate a new one, but the issue still occurs)*
